Repository wecode-bootcamp-korea/20-1st-WESOP-frontend, pull requests merged in 2021-05, with the labels that each got.

#9 [20기 김도은] Footer / Refactor: 리뷰 반영 완료
  public/index.html
  src/Components/Footer/Footer.js
  src/Components/Footer/Footer.scss
  src/Pages/Main/Main.js
Labels: Status: Accepted

#1 [20기 김도은] Refactor: 리뷰 반영 완료
  public/data/productMockdata.json
  public/images/illust.png
  public/images/wesop.png
  public/index.html
  src/Components/MainIllust/MainIllust.js
  src/Components/MainIllust/MainIllust.scss
  src/Components/MainProduct/MainProduct.js
  src/Components/MainProduct/MainProduct.scss
  src/Components/ProductList/ProductList.js
  src/Components/ProductList/ProductList.scss
  src/Pages/Main/Main.js
  src/Styles/common.scss
  src/Styles/variables.scss
Labels: Status: Accepted

#5 [20기 김도은] Refactor: 빠진 key값 추가
  public/data/menuMockdata.json
  public/images/closeBtn.png
  src/Components/Footer/Footer.js
  src/Components/MainIllust/MainIllust.js
  src/Components/MainMenu/FirstMenu/FirstMenu.js
  src/Components/MainMenu/FirstMenu/FirstMenu.scss
  src/Components/MainMenu/MainMenu.js
  src/Components/MainMenu/MainMenu.scss
  src/Components/MainMenu/SecondMenu.js/SecondMenu.js
  src/Components/MainMenu/SecondMenu.js/SecondMenu.scss
  src/Components/MainMenu/ThirdMenu/ThirdMenu.js
  src/Components/MainMenu/ThirdMenu/ThirdMenu.scss
  src/Components/MainProduct/MainProduct.js
  src/Components/MenuColumn/MenuColumn.js
  src/Components/MenuColumn/MenuColumn.scss
  src/Components/Nav/Nav.js
  src/Components/Nav/Nav.scss
  src/Pages/Main/Main.js
  src/Pages/Main/Main.scss
  src/Pages/Product/Product.js
  src/Styles/variables.scss
Labels: Status: 리뷰 요청

#2 [20기 김휘성] 상품 상세정보 컴포넌트 구현중
  public/data/mockdata.json
  src/Components/Detail/Detail.js
  src/Components/Detail/Detail.scss
  src/Components/FilterBar/FilterBar.js
  src/Pages/ProductDetail/ProductDetail.js
  src/Routes.js
  src/Styles/common.scss
Labels: Status: 리뷰 요청, Status: 추가 기능 구현중

#6 [20기 김휘성] 기프트 리스트 컴포넌트 완료
  public/data/mockdata.json
  public/data/productMockdata.json
  src/Components/GiftList/Gift/Gift.js
  src/Components/GiftList/Gift/Gift.scss
  src/Components/GiftList/GiftList.js
  src/Components/GiftList/GiftList.scss
  src/Pages/GiftProductList/GiftProductList.js
  src/Routes.js
Labels: Status: 리뷰 요청

#12 [20기 김도은] main menu / Add: 동적라우팅 추가
  public/data/category_id=1.json
  public/data/menu_id=1.json
  public/images/illust2.png
  src/Components/MainIllust/MainIllust.js
  src/Components/MainMenu/FirstMenu/FirstMenu.js
  src/Components/MainMenu/MainMenu.js
  src/Components/MainMenu/SecondMenu.js/SecondMenu.js
  src/Components/MainMenu/ThirdMenu/ThirdMenu.js
  src/Components/MenuColumn/MenuColumn.scss
  src/Pages/Products/Products.js
  src/Routes.js
Labels: Status: 리뷰 요청

#13 [20기 김도은] Add: Cart 추가
  public/images/Close.png
  src/Components/Cart/Cart.js
  src/Components/Cart/Cart.scss
  src/Components/Detail/Detail.js
  src/Components/GiftList/Gift/Gift.scss
  src/Components/MainMenu/MainMenu.js
  src/Components/MenuColumn/MenuColumn.js
  src/Components/Nav/Nav.js
  src/Components/Nav/Nav.scss
  src/Components/NeedLogin/NeedLogin.js
  src/Components/NeedLogin/NeedLogin.scss
  src/Components/OrderList/OrderList.js
  src/Components/OrderList/OrderList.scss
  src/Components/ProductList/ProductList.js
  src/Pages/GiftPage/GiftPage.js
  src/Routes.js
Labels: Status: 리뷰 요청

#3 [20기 최원근] Login 페이지 (Refactoring)
  src/Components/Login/Form.js
  src/Components/Login/Login.js
  src/Components/Login/Login.scss
  src/Pages/Main/Main.js
Labels: Status: 리뷰 요청

#11 [20기 최원근] 사용법_상세페이지 구현
  public/data/product:1.json
  public/images/leftProduct.png
  src/Components/HowToUse/HowToUse.js
  src/Components/HowToUse/HowToUse.scss
  src/Components/MainProduct/MainProduct.js
  src/Components/MockData.js
  src/Pages/ProductDetail/ProductDetail.scss
Labels: Status: 리뷰 요청

#10 [20기 김휘성] FilterBar 컴포넌트 컨플릭트 해결
  public/data/mockdata.json
  public/images/DownArrow.png
  src/Components/FilterBar/FilterBar.js
  src/Components/FilterBar/FilterBar.scss
  src/Components/FilterBarExtend/FilterBarExtend.js
  src/Components/FilterBarExtend/FilterBarExtend.scss
  src/Components/FilterBtn/FilterBtnClose.js
  src/Components/FilterBtn/FilterBtnClose.scss
  src/Components/FilterBtn/FilterBtnOpen.js
  src/Components/FilterBtn/FilterBtnOpen.scss
  src/Components/GiftList/Gift/Gift.js
  src/Pages/GiftPage/GiftPage.js
  src/Pages/Main/Main.js
Labels: Status: 리뷰 요청

#14 [20기 최원근] 회원가입 페이지 (Refactoring)
  src/Components/SignUp/Form/AddForm.js
  src/Components/SignUp/Form/BaseForm.js
  src/Components/SignUp/SignUp.js
  src/Components/SignUp/SignUp.scss
  src/Pages/Main/Main.js
Labels: Status: 리뷰 요청
